services:
  keeptabs:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "7070:8080"
    networks:
      - keeptabs-network
  database:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - keeptabs-network
    volumes:
      - mongo_data:/data/db

networks:
  keeptabs-network:
volumes:
  mongo_data: