services:
  keeptabs:
    image: keeptabs
    build:
      context: .
      dockerfile: KeepTabs/Dockerfile
    networks:
      - keeptabs-network
    ports:
      - "8080:8080"

  keeptabs.worker:
    image: keeptabs.worker
    build:
      context: .
      dockerfile: KeepTabs.Worker/Dockerfile
    networks:
      - keeptabs-network

networks:
  keeptabs-network: