// <auto-generated />
using System;
using KeepTabs.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeepTabs.Database.Migrations;

[DbContext(typeof(KeepTabsDbContext))]
[Migration("20250614085803_RenameJobTrackingTableToMonitor")]
partial class RenameJobTrackingTableToMonitor
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("KeepTabs.Entities.Monitor", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("text");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("JobTitle")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("JobUrl")
                .IsRequired()
                .HasColumnType("text");

            b.Property<int>("RequestInterval")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.ToTable("Monitors");
        });

        modelBuilder.Entity("KeepTabs.Entities.ResponseStatus", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("MonitorId")
                .IsRequired()
                .HasColumnType("text");

            b.Property<double>("ResponseLatency")
                .HasColumnType("double precision");

            b.Property<int>("RunningState")
                .HasColumnType("integer");

            b.Property<string>("RunningStateName")
                .IsRequired()
                .HasColumnType("text");

            b.Property<int?>("StatusCode")
                .HasColumnType("integer");

            b.Property<string>("StatusMessage")
                .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("MonitorId");

            b.ToTable("ResponseStatuses");
        });

        modelBuilder.Entity("KeepTabs.Entities.ResponseStatus", b =>
        {
            b.HasOne("KeepTabs.Entities.Monitor", "Monitor")
                .WithMany("ResponseStatuses")
                .HasForeignKey("MonitorId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Monitor");
        });

        modelBuilder.Entity("KeepTabs.Entities.Monitor", b =>
        {
            b.Navigation("ResponseStatuses");
        });
#pragma warning restore 612, 618
    }
}